networks:
  docker_net:
    external: true

services:
  postgres-test-auth-db:
    image: postgres:16-alpine
    hostname: postgres-test-auth-db
    container_name: postgres-test-auth-db
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_DB: "dev"
      POSTGRES_PASSWORD: "dev"
    ports:
      - "54323:5432"
    networks:
      - docker_net