### POST sing-up
POST {{host}}/auth/sing-up
Content-Type: application/json

{
  "fullName": "Vlad Kiselev",
  "email": "trololo55721@gmail.com",
  "phone": "79633028230",
  "password": "123321"
}

### GET confirm
GET {{host}}/auth/confirm-email?user=133f8725-f175-448c-a167-816db119a562
Content-Type: application/json

### POST sing-in
POST {{host}}/auth/sing-in
Content-Type: application/json

{
  "email": "trololo55721@gmail.com",
  "password": "123321"
}