### POST sing-up
POST {{host}}/auth/sing-up
Content-Type: application/json

{
  "fullName": "Vlad Kiselev",
  "email": "trololo55723@gmail.com",
  "phone": "79633028231",
  "password": "123321"
}

### GET confirm
GET {{host}}/auth/confirm-email?user=dd173b77-25bf-4034-9984-e4bcd74e2e69
Content-Type: application/json

### POST sing-in
POST {{host}}/auth/sing-in
Content-Type: application/json

{
  "email": "trololo55723@gmail.com",
  "password": "123321"
}